Repository 1christianfelix/raynian, pull requests merged in 2023-07, with the labels that each got.

#33 fix modal closing on mouse up
  raynian-fe/src/components/util/Modal.jsx
Labels: bug

#36 [RAYN-38,64][#15] Google OAuth FE BE setup
  backend-fe/models/UserModel.js
  backend-fe/package-lock.json
  backend-fe/package.json
  backend-fe/passport.js
  backend-fe/routes/auth.js
  backend-fe/server.js
  backend-fe/util/usernameGen.js
  backend-fe/util/wordArrays.js
  package-lock.json
  raynian-fe/src/App.js
  raynian-fe/src/components/pages/LoginPage.jsx
  raynian-fe/src/components/pages/OAuthLoginSuccess.jsx
  raynian-fe/src/components/pages/SignupPage.jsx
  raynian-fe/src/context/ModalContext.js
Labels: backend, frontend

#40 [RAYN-37]Timer functions
  raynian-fe/src/components/pages/Dashboard.jsx
  raynian-fe/src/components/util/Modal.jsx
  raynian-fe/src/components/util/Timer.jsx
  raynian-fe/src/components/util/TimerSettings.jsx
  raynian-fe/src/context/TimerContext.js
Labels: frontend

#41 [RAYN-69,70,71]Timer ux
  raynian-fe/package-lock.json
  raynian-fe/package.json
  raynian-fe/src/components/navigation/Nav.jsx
  raynian-fe/src/components/pages/Dashboard.jsx
  raynian-fe/src/components/util/Timer.jsx
  raynian-fe/src/components/util/TimerSettings.jsx
  raynian-fe/src/context/DarkLightContext.js
  raynian-fe/src/context/TimerContext.js
  raynian-fe/src/index.css
Labels: frontend
